---
title: "Reading from Petrel"
output:
  html_document:
    df_print: paged
---

```{r setup, include = FALSE, error=TRUE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      comment = "#>",
                      collapse = TRUE,
                      error = TRUE,
                      warning = FALSE,
                      message = FALSE,
                      fig.align = 'center'
                      )
```


## Read file

```{r}
# read the Petrel/Eclipse file. Assign it to tbl object
tbl <- read.csv("wellRegion.GRDECL", skip = 1, header = FALSE, 
         stringsAsFactors = FALSE, strip.white = TRUE)
tbl
```


```{r}
# convert string to character vectors.
alist_vectors <- lapply(tbl$V1, function(x) unlist(strsplit(x, " ")))
alist_vectors[[1]]  # show a sample
```

```{r}
# show the number of elements in each row
len_str <- unlist(lapply(tbl$V1, function(x) 
    length(unlist(strsplit(trimws(x), " ")))))

head(len_str)
tail(len_str)
length(len_str)   # total number of rows in the file
```

## Examples

```{r}
# get only elements with asterisk in row 1
grep("\\*[0-9]{1,2}", alist_vectors[[1]], value = TRUE, perl=TRUE)
```

```{r}
# get elements with asterisk in row 1417
grep("\\*[0-9]{1,2}", alist_vectors[[1417]], value = TRUE, perl=TRUE)
```

## Extract only numbers that have asterik in the middle

```{r}
# extract with regex
wanted <- lapply(alist_vectors, function(x) grep("\\*[0-9]{1,2}", x, 
                                                 value = TRUE, perl=TRUE))
wanted[[1]]   # show a sample
```



```{r}
# extract row and values. Method #1
df <- data.frame()
invisible(lapply(seq_along(wanted), function(x) {
    r <- data.frame(row=x, value=wanted[[x]], stringsAsFactors = FALSE)
    df <<- rbind(df, r)
}))
df
```



```{r}
# extract row and values. Method #2
df <- data.frame()
for (i in 1:length(wanted)) {
    x <- data.frame(row=i, value=wanted[[i]], stringsAsFactors = FALSE)
    df <- rbind(df, x)
}
df
```

```{r rows.print=25}
# get specific row from the original file
library(dplyr)

df %>% 
    filter(row==1)
```

```{r rows.print=25}
# another way to extract row 1
df[df$row==1,]
```


